# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9942d9d083cf1b5c686e034b58415e811028408fd7df02e00982bd9642c39b58898438248f6b85585dce637e7fe325de629ca0c61817fc9decae40a6211e9ab7

test:
  secret_key_base: 3b92631bc239cb33a0d9859de99042b013162b66b19dfcbeb7fe53fc094b80286b59950e8d78ad47ff6edb1ea434b296fc2e794e55aa4b8fb52b7a90a66f0ec0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
